# main.py                                                           #
# QURU ~ Final Year Project 2019                                    #
# Sukkur IBA University                                             #
# Developer: Mohammad Usama                                         #
# Version: Final Script                                             #
#####################################################################

import timeit
import numpy as np

import textRank
import ExtractKeyWords
import IdentifyTopic
import generateDistractors

# time for logging
startTime = timeit.default_timer()

fileText = ""

# Load file named input.txt from this directory
try:
    file = open("input.txt", "r",encoding='utf-8-sig')
    fileText = file.read()
except:
    file = open("input.txt","r")
    fileText = file.read()
file.close()

# limit identifies how many questions will be generated
limit=10


# Rank each sentence
sentences,raw_sentences,gloveDictionary = textRank.tokenize_sentences(fileText)

# sentences are ranked individual actual sentences
# raw_sentences are corresponding cleaned sentences will be used for answer and distractor generation later

# slicing sentences and raw sentences
if len(sentences)<limit:
    limit = len(sentences)
sentences = sentences[:limit]
raw_sentences = raw_sentences[:limit]
print(raw_sentences)

# Extract Keywords
keywords = ExtractKeyWords.getKeyWords(sentences,raw_sentences)

# Topic Identification  ----- Was done to partially identify topic but not used in project
topic = IdentifyTopic.getTopic(raw_sentences)

print("Topic is: "+topic)

# Distractors generation
#     Input to this module are keywords and glove Dictionary obtained from ExtractKeyWords and textRank respectively
optAnsArr=generateDistractors.getDistractors_By_Glove(keywords,gloveDictionary)




# Finalaizing Results as an xml file

print("Finalizing Results")
import re
import xml.etree.ElementTree as xml

filename = "test_xml.xml"
nrootTag = xml.Element("ResultsDoc")
nrootTag.text = "Topic with MCQS generated by QURU"
topicTag = xml.Element("topic")
topicTag.text = fileText
nrootTag.append(topicTag)
i=0
for line in sentences:
    if keywords[i][0] == "null":
        continue
    else:
        src_str = re.compile(keywords[i][0], re.IGNORECASE)
        sen = str(sentences[i])
        questionTag = xml.Element("question")
        quesTag = xml.SubElement(questionTag, "ques")
        # questionTag.text=sen.replace(keywords[i][j],'________________')
        quesTag.text = src_str.sub('________________', sen)
        answerTag = xml.SubElement(questionTag, "answer")
        answerTag.text = keywords[i][0]
        ii=1
        for option in optAnsArr[i]:
            optionTag = xml.SubElement(questionTag, "option"+str(ii))
            optionTag.text = option
            ii+=1
        ii=0

    nrootTag.append(questionTag)
    i+=1

tree = xml.ElementTree(nrootTag)
# File storage directory of PHP server
tree.write("../questions22.xml")
tree.write("questions22.xml")
print("Finished Processing")

# Finished Log Time
loading_time = timeit.default_timer() - startTime
print("MCQ Generation Time: {}".format(loading_time))
